### ISSUE TITLE
Blocks Falling

### ISSUE THREAD

**Issue by MesameruNayami** [TheRealCatherine/StageMechanic#25] opened 2018-01-06 04:58 UTC
Blocks fall into different positions when the same block is pushed.  The first screenshot is before doing anything, the other three are after pushing the block in front of player in before, undoing, then pushing again.  Each time they fall into different positions.

![before](https://user-images.githubusercontent.com/34995834/34636622-73b30c08-f26b-11e7-9606-67c954ea725f.png)
![after ex3](https://user-images.githubusercontent.com/34995834/34636623-74885bb0-f26b-11e7-902f-1061429196ba.png)
![after ex1](https://user-images.githubusercontent.com/34995834/34636620-7147b748-f26b-11e7-97a3-56ecae5bf45e.png)
![after ex2](https://user-images.githubusercontent.com/34995834/34636621-72779e94-f26b-11e7-9419-f30441222434.png)

**Comment by TheRealCatherine** [comment] 2018-01-06 15:16
Which level file is this?

**Comment by MesameruNayami** [comment] 2018-01-06 15:19
It's level twenty-three.  I have noticed it does occasionally happen from time to time, though I didn't notice it that strongly until that level, simply thought I had messed up somewhere in the design of the level at the time.

**Comment by TheRealCatherine** [comment] 2018-01-10 21:16
Video showing the problem: https://www.youtube.com/watch?v=7MIXA2vWHiI

**Comment by TheRealCatherine** [comment] 2018-01-11 20:00
thought I had it fixed for a moment there, but no

the issue is that if there is a block supporting another block and the supporting block begins to fall it can take a few frames before the supported block begins to fall. this effect is more pronounced when higher blocks are earlier in the BlockManager hierarchy but sorting only helps slightly and doesn't fix the underlying issue. 

one option is to compute all block gravity all at once either every other frame or in another thread but this breaks genericness of the engine to a degree.

**Comment by TheRealCatherine** [comment] 2018-01-30 18:21
should be fixed now but still needs testing

**Closed as completed** 2018-01-30 18:42 UTC
Labels: bug, block movement, play mode, block mechanics
